name: api-deploy-stg

on:
  workflow_call:

jobs:
  # This workflow contains a single job called "build"
  deploy-stg:
    runs-on: ubuntu-latest
    container: f3capital/aquario:latest
    env:
      AZURE_CLIENT_SECRET: ${{secrets.AZURE_CLIENT_SECRET_STG}}
      AZURE_CLIENT_ID: ${{secrets.AZURE_CLIENT_ID_STG}}
      AZURE_REGION: ${{secrets.AZURE_REGION_STG}}
      AZURE_STAGE: ${{secrets.AZURE_STAGE_STG}}
      DATABASE_HOST: ${{secrets.DATABASE_HOST_STG}}
      AZURE_RESOURCE_GROUP: ${{secrets.AZURE_RESOURCE_GROUP_STG}}
      APPINSIGHTS_INSTRUMENTATIONKEY: ${{secrets.APPINSIGHTS_INSTRUMENTATIONKEY_STG}}
      DATABASE_USERNAME: ${{secrets.DATABASE_USERNAME_STG}}
      DATABASE_PASSWORD: ${{secrets.DATABASE_PASSWORD_STG}}
      DATABASE_NAME: ${{secrets.DATABASE_NAME_STG}}
      KEYCLOAK_URL: ${{secrets.KEYCLOAK_URL_STG}}
      KEYCLOAK_USERNAME_ADMIN: ${{secrets.KEYCLOAK_USERNAME_ADMIN_STG}}
      KEYCLOAK_PASSWORD_ADMIN: ${{secrets.KEYCLOAK_PASSWORD_ADMIN_STG}}
      AZURE_FUNCTIONS_APP_ID: ${{secrets.AZURE_FUNCTIONS_APP_ID_STG}}
      AZURE_FUNCTIONS_SECRET: ${{secrets.AZURE_FUNCTIONS_SECRET_STG}}
      #------------------------------------------------------------#
      AZURE_SUBSCRIPTION_ID: ${{secrets.AZURE_SUBSCRIPTION_ID}}
      AZURE_TENANT_ID: ${{secrets.AZURE_TENANT_ID}}
      KEYCLOAK_USERNAME_TEST: ${{secrets.KEYCLOAK_USERNAME_TEST}}
      KEYCLOAK_PASSWORD_TEST: ${{secrets.KEYCLOAK_PASSWORD_TEST}}
      KEYCLOAK_CLIENT_SECRET_TEST: ${{secrets.KEYCLOAK_CLIENT_SECRET_TEST}}
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          
      - name: Install
        run: |
          npm config set registry ${{secrets.ARTIFACTORY_NPM_REGISTRY}}
          npm config set -- '_auth' "${{secrets.ARTIFACTORY_AUTH}}"
          npm config set -- 'email' "${{secrets.ARTIFACTORY_EMAIL}}"
          npm config set -- 'always-auth' "true"
          yarn install
      
      - name: Deploy STG 
        run: |
          sls package
          az login --service-principal --username ${{secrets.AZURE_FUNCTIONS_APP_ID_STG}} --password ${{secrets.AZURE_FUNCTIONS_SECRET_STG}} --tenant ${{secrets.AZURE_TENANT_ID}}
          az functionapp deployment source config-zip -g ${{secrets.AZURE_RESOURCE_GROUP_STG}} -n aquario-eus2-stg-auth-service --src .serverless/auth-service.zip
          sls deploy
          az functionapp deployment source config-zip -g ${{secrets.AZURE_RESOURCE_GROUP_STG}} -n aquario-eus2-stg-auth-service --src .serverless/auth-service.zip
