name: api-deploy-sbx

on:
  workflow_call:
    inputs:
      APP_NAME:
        type: string
        required: true

jobs:
  deploy-sbx:
    if: github.ref == 'refs/heads/sbx'
    runs-on: ubuntu-latest
    container: f3capital/aquario:latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    env:
      AZURE_SUBSCRIPTION_ID: ${{secrets.AZURE_SUBSCRIPTION_ID}}
      AZURE_TENANT_ID: ${{secrets.AZURE_TENANT_ID}}
      AZURE_CLIENT_ID: ${{secrets.AZURE_CLIENT_ID_SBX}}
      AZURE_CLIENT_SECRET: ${{secrets.AZURE_CLIENT_SECRET_SBX}}
      AZURE_REGION: ${{secrets.AZURE_REGION_SBX}}
      AZURE_STAGE: ${{secrets.AZURE_STAGE_SBX}}
      AZURE_RESOURCE_GROUP: ${{secrets.AZURE_RESOURCE_GROUP_SBX}}

      APPINSIGHTS_INSTRUMENTATIONKEY: ${{secrets.APPINSIGHTS_INSTRUMENTATIONKEY_SBX}}
      
      DATABASE_HOST: ${{secrets.DATABASE_HOST_SBX}}
      DATABASE_USERNAME: ${{secrets.DATABASE_USERNAME_SBX}}
      DATABASE_PASSWORD: ${{secrets.DATABASE_PASSWORD_SBX}}
      DATABASE_NAME: ${{secrets.DATABASE_NAME_SBX}}
      
      KEYCLOAK_URL: ${{secrets.KEYCLOAK_URL_SBX}}
      KEYCLOAK_USERNAME_ADMIN: ${{secrets.KEYCLOAK_USERNAME_ADMIN_SBX}}
      KEYCLOAK_PASSWORD_ADMIN: ${{secrets.KEYCLOAK_PASSWORD_ADMIN_SBX}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          
      - name: Install
        run: |
          npm config set registry ${{secrets.ARTIFACTORY_NPM_REGISTRY}}
          npm config set -- '_auth' "${{secrets.ARTIFACTORY_AUTH}}"
          npm config set -- 'email' "${{secrets.ARTIFACTORY_EMAIL}}"
          npm config set -- 'always-auth' "true"
          yarn install
      
      - name: Sandbox Deploy
        run: |
          sls package
          az login --service-principal --username ${{secrets.AZURE_FUNCTIONS_APP_ID_SBX}} --password ${{secrets.AZURE_FUNCTIONS_SECRET_SBX}} --tenant ${{secrets.AZURE_TENANT_ID}}
          az functionapp deployment source config-zip -g ${{secrets.AZURE_RESOURCE_GROUP_DEV}} -n aquario-eus2-sbx-${{inputs.APP_NAME}} --src .serverless/${{inputs.APP_NAME}}.zip
          sls deploy
          az functionapp deployment source config-zip -g ${{secrets.AZURE_RESOURCE_GROUP_DEV}} -n aquario-eus2-sbx-${{inputs.APP_NAME}} --src .serverless/${{inputs.APP_NAME}}.zip
