name: api-deploy-aws-dev

on:
  workflow_call:
    secrets:
      ARTIFACTORY_NPM_REGISTRY:
        required: true
      ARTIFACTORY_AUTH:
        required: true
      ARTIFACTORY_EMAIL:
        required: true
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_REGION:
        required: true
      DD_API_KEY:
        required: true
      LOG_LEVEL:
        required: true
      ENV_DEV:
        required: true
        
      AWS_DYNAMODB_REGION:
        required: false
      AWS_DYNAMODB_VERSION:
        required: false
      AWS_DYNAMODB_MIRRORED_DOCUMENTS_TABLE:
        required: false
      AWS_LAMBDA_TRIGGER_STEP_FUNCTION_ARN:
        required: false

jobs:
  deploy-dev:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    env:
      DATABASE_HOST: ${{secrets.DATABASE_HOST_DEV}}
      DATABASE_USERNAME: ${{secrets.DATABASE_USERNAME_DEV}}
      DATABASE_PASSWORD: ${{secrets.DATABASE_PASSWORD_DEV}}
      DATABASE_NAME: ${{secrets.DATABASE_NAME_DEV}}

      KEYCLOAK_URL: ${{secrets.KEYCLOAK_URL_DEV}}
      KEYCLOAK_USERNAME_ADMIN: ${{secrets.KEYCLOAK_USERNAME_ADMIN_DEV}}
      KEYCLOAK_PASSWORD_ADMIN: ${{secrets.KEYCLOAK_PASSWORD_ADMIN_DEV}}
      
      LOG_LEVEL: ${{secrets.LOG_LEVEL_DEV}}
      DD_API_KEY: ${{secrets.DD_API_KEY}}
      DD_ENV: ${{secrets.ENV_DEV}}
      
      AWS_DYNAMODB_REGION: ${{secrets.AWS_REGION_DEV}}
      AWS_DYNAMODB_VERSION: ${{secrets.AWS_DYNAMODB_VERSION_DEV}}
      AWS_DYNAMODB_MIRRORED_DOCUMENTS_TABLE: ${{secrets.AWS_DYNAMODB_MIRRORED_DOCUMENTS_TABLE_DEV}}
      AWS_LAMBDA_TRIGGER_STEP_FUNCTION_ARN: ${{secrets.AWS_LAMBDA_TRIGGER_STEP_FUNCTION_ARN_DEV}}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          
      - name: Install
        run: |
          npm config set registry ${{secrets.ARTIFACTORY_NPM_REGISTRY}}
          npm config set -- '_auth' "${{secrets.ARTIFACTORY_AUTH}}"
          npm config set -- 'email' "${{secrets.ARTIFACTORY_EMAIL}}"
          npm config set -- 'always-auth' "true"
          yarn install
      
      - name: Export AWS Config
        run: |
          export AWS_ACCESS_KEY_ID=${{secrets.AWS_ACCESS_KEY_ID_DEV}}
          export AWS_SECRET_ACCESS_KEY=${{secrets.AWS_SECRET_ACCESS_KEY_DEV}}
          export AWS_REGION=${{secrets.AWS_REGION_DEV}}

      - name: Development Deploy 
        uses: serverless/github-action@master
        with:
          args: deploy --stage ${{secrets.AWS_REGION_DEV}}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          
